### ISSUE TITLE
Mudar o conteúdo da tabela.

### ISSUE THREAD

**Issue by bmq-commits** [msmoserbru/formacao_github17#3]
Acho que as seções de cards e demais sites poderiam ficar dentro da tabela para melhor organização.

![image](https://github.com/user-attachments/assets/7fe097c4-90d2-4c2c-9f2e-8ee357bec292)

Thanks!

**Comment by msmoserbru** [comment]
Olá!
Boa idéia.
Vamos fazer, obrigada!
